# make keebio/chocopad/rev2:lamsyl
# Enter the bootloader by pressing QK_BOOT or the physical reset button
# Put the following file into the volume RPI-RP2
# qmk_firmware/.build/keebio_chocopad_rev2_lamsyl.uf2

all:
	$(MAKE) -C ../../../../.. $@
%:
	$(MAKE) -C ../../../../.. $@
